### ISSUE TITLE
Neo4j fails to start when Graphaware plugin is enabled

### ISSUE THREAD

**Issue by ludydoo** [graphaware/neo4j-framework#32]
Hi,

I installed neo4j with homebrew to try it out, then I wanted to insatall the node-uuid plugin which states that I must install the graphaware framework.

This is my neo4j info
```
Neo4j Server is running at pid 38988
Using Java version: CurrentJDK
NEO4J_HOME:        /usr/local/Cellar/neo4j/2.3.0/libexec
NEO4J_SERVER_PORT: 7474
NEO4J_INSTANCE:    /usr/local/Cellar/neo4j/2.3.0/libexec
JAVA_HOME:         /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
JAVA_OPTS:         -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:hashCode=5 -Dneo4j.ext.udc.source=tarball -Dneo4j.ext.udc.source=homebrew -Djava.awt.headless=true
CLASSPATH:         /usr/local/Cellar/neo4j/2.3.0/libexec/lib/commons-lang3-3.3.2.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/concurrentlinkedhashmap-lru-1.4.2.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/jline-2.12.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/lucene-core-3.6.2.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-codegen-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-consistency-check-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-consistency-check-legacy-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-csv-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-cypher-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-cypher-compiler-1.9_2.11-2.0.5.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-cypher-compiler-2.2_2.11-2.2.6.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-cypher-compiler-2.3-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-cypher-frontend-2.3-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-function-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-graph-algo-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-graph-matching-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-import-tool-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-io-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-jmx-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-kernel-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-logging-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-lucene-index-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-primitive-collections-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-shell-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-udc-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/neo4j-unsafe-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/opencsv-2.3.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/parboiled-core-1.1.7.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/parboiled-scala_2.11-1.1.7.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/scala-library-2.11.7.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/scala-parser-combinators_2.11-1.0.4.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/scala-reflect-2.11.7.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/lib/server-api-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/asm-5.0.2.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/bcprov-jdk15on-1.52.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/commons-beanutils-1.8.3.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/commons-configuration-1.10.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/commons-digester-2.1.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/commons-io-2.4.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/commons-lang-2.6.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/commons-logging-1.1.1.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jackson-core-asl-1.9.13.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jackson-jaxrs-1.9.13.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jackson-mapper-asl-1.9.13.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/javax.servlet-api-3.1.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jersey-core-1.19.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jersey-multipart-1.19.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jersey-server-1.19.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jersey-servlet-1.19.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jetty-http-9.2.4.v20141103.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jetty-io-9.2.4.v20141103.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jetty-security-9.2.4.v20141103.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jetty-server-9.2.4.v20141103.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jetty-servlet-9.2.4.v20141103.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jetty-util-9.2.4.v20141103.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jetty-webapp-9.2.4.v20141103.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jetty-xml-9.2.4.v20141103.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/jsr311-api-1.1.2.r612.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/logback-access-1.1.2.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/logback-classic-1.1.2.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/logback-core-1.1.2.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/mimepull-1.9.3.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/neo4j-browser-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/neo4j-server-2.3.0-static-web.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/neo4j-server-2.3.0.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/netty-all-4.0.28.Final.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/rhino-1.7R4.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/rrd4j-2.2.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/system/lib/slf4j-api-1.7.6.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/plugins/graphaware-server-community-all-2.2.6.35.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/plugins/graphaware-uuid-2.2.6.35.7.jar:/usr/local/Cellar/neo4j/2.3.0/libexec/conf
```

Then, I added `graphaware-uuid-2.2.6.35.7.jar`and `graphaware-server-community-all-2.2.6.35.jar` into `usr/local/Cellar/neo4j/2.3.0/libexec/`

```
me$ ls -al ./../plugins
total 25824
drwxr-xr-x   6 me  wheel       204 21 oct 17:25 .
drwxr-xr-x  11 me  admin       374 21 oct 16:28 ..
-rw-r--r--@  1 me  wheel      6148 21 oct 17:30 .DS_Store
-rw-r--r--   1 me  wheel       273 16 oct 17:20 README.txt
-rw-r-----@  1 me  wheel  13191699 21 oct 16:27 graphaware-server-community-all-2.2.6.35.jar
-rw-r-----@  1 me  wheel     13870 21 oct 16:29 graphaware-uuid-2.2.6.35.7.jar
```

And as the node-uuid plugins states, I add this to `neo4j.properties`

```
cat neo4j.properties 
################################################################
# Neo4j
#
# neo4j.properties - database tuning parameters
#
################################################################

# Enable this to be able to upgrade a store from an older version.
#allow_store_upgrade=true

# The amount of memory to use for mapping the store files, in bytes (or
# kilobytes with the 'k' suffix, megabytes with 'm' and gigabytes with 'g').
# If Neo4j is running on a dedicated server, then it is generally recommended
# to leave about 2-4 gigabytes for the operating system, give the JVM enough
# heap to hold all your transaction state and query context, and then leave the
# rest for the page cache.
# The default page cache memory assumes the machine is dedicated to running
# Neo4j, and is heuristically set to 50% of RAM minus the max Java heap size.
#dbms.pagecache.memory=10g

# Enable this to specify a parser other than the default one.
#cypher_parser_version=2.0

# Set the root directory for use with file URLs (`file:///`) in LOAD CSV.
# If enabled, file URLs will refer to locations inside the `data/import`
# directory. I.e. `file:///movies/actors.csv` will load from the file
# `data/import/movies/actors.csv`.
#dbms.security.load_csv_file_url_root=data/import

# Keep logical logs, helps debugging but uses more disk space, enabled for
# legacy reasons To limit space needed to store historical logs use values such
# as: "7 days" or "100M size" instead of "true".
#keep_logical_logs=7 days

# Enable shell server so that remote clients can connect via Neo4j shell.
#remote_shell_enabled=true
# The network interface IP the shell will listen on (use 0.0.0.0 for all interfaces).
#remote_shell_host=127.0.0.1
# The port the shell will listen on, default is 1337.
#remote_shell_port=1337

# NODE UUID CONFIGURATION
com.graphaware.runtime.enabled=true

#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

#optional, default is uuid:
#com.graphaware.module.UIDM.uuidProperty=uuid

#optional, default is all nodes:
#com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')

#optional, default is uuidIndex
#com.graphaware.module.UIDM.uuidIndex=uuidIndex
```
But when i exec `neo4j restart`

I get this error

```
ERROR: Neo4j Server not running
Starting Neo4j Server...WARNING: not changing user
process [39496]... waiting for server to be ready... Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.
```

The log file 

```
cat ./../data/log/console.log 
17:34:33.744 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
17:34:35.200 [main] INFO  c.g.r.b.RuntimeKernelExtension - GraphAware Runtime enabled, bootstrapping...
2015-10-21 17:34:35.233-0400 INFO  Successfully shutdown Neo4j Server
2015-10-21 17:34:35.234-0400 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@20b30726' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@20b30726' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@20b30726' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:67)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:234)
	at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:100)
	at org.neo4j.server.CommunityBootstrapper.start(CommunityBootstrapper.java:48)
	at org.neo4j.server.CommunityBootstrapper.main(CommunityBootstrapper.java:35)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@20b30726' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:538)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:109)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:194)
	... 3 more
	Suppressed: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /usr/local/Cellar/neo4j/2.3.0/libexec/data/graph.db
		at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:143)
		at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:43)
		at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
		at org.neo4j.server.CommunityNeoServer$1.newGraphDatabase(CommunityNeoServer.java:66)
		at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:95)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:528)
		... 5 more
	Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.graphaware.runtime.bootstrap.RuntimeKernelExtension@2a495dad' was successfully initialized, but failed to start. Please see attached cause exception.
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:538)
		at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:109)
		at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:528)
		at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:109)
		at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:139)
		... 10 more
		Suppressed: java.lang.NoSuchMethodError: org.neo4j.kernel.impl.core.NodeManager.newGraphProperties()Lorg/neo4j/kernel/impl/core/GraphPropertiesImpl;
			at com.graphaware.common.kv.GraphKeyValueStore.<init>(GraphKeyValueStore.java:32)
			at com.graphaware.runtime.metadata.GraphPropertiesMetadataRepository.<init>(GraphPropertiesMetadataRepository.java:55)
			at com.graphaware.runtime.GraphAwareRuntimeFactory.createRuntime(GraphAwareRuntimeFactory.java:62)
			at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:111)
			at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:528)
			... 15 more
	[CIRCULAR REFERENCE:java.lang.NoSuchMethodError: org.neo4j.kernel.impl.core.NodeManager.newGraphProperties()Lorg/neo4j/kernel/impl/core/GraphPropertiesImpl;]
	[CIRCULAR REFERENCE:java.lang.NoSuchMethodError: org.neo4j.kernel.impl.core.NodeManager.newGraphProperties()Lorg/neo4j/kernel/impl/core/GraphPropertiesImpl;]
	[CIRCULAR REFERENCE:java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /usr/local/Cellar/neo4j/2.3.0/libexec/data/graph.db]
```

**Comment by MicTech** [comment]
Your problem is in the different versions of Neo4j and GraphAware plugins.

Neo4j - 2.3.0
GA plugins - 2.2.6.x.x

Those version must be the same. Please download correct version from [http://products.graphaware.com/](http://products.graphaware.com/)

**Comment by bachmanm** [comment]
It's gonna take us a few days to release a version compatible with 2.3.0, which was just released
