### ISSUE TITLE
[Neo4j 2.3 - Community] Http logging causes ClassCastException at start

### ISSUE THREAD

**Issue by sylvainroussy** [graphaware/neo4j-framework#36]
Hi,

When activating "org.neo4j.server.http.log.enabled=true" the Neo4j server failed to start:

2015-11-15 19:01:50.353+0100 ERROR Failed to start Neo4j: Starting Neo4j failed: org.eclipse.jetty.server.handler.RequestLogHandler cannot be cast to org.eclipse.jetty.server.handler.HandlerList Starting Neo4j failed: org.eclipse.jetty.server.handler.RequestLogHandler cannot be cast to org.eclipse.jetty.server.handler.HandlerList
org.neo4j.server.ServerStartupException: Starting Neo4j failed: org.eclipse.jetty.server.handler.RequestLogHandler cannot be cast to org.eclipse.jetty.server.handler.HandlerList
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:67)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:234)
	at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:100)
	at org.neo4j.server.CommunityBootstrapper.start(CommunityBootstrapper.java:48)
	at org.neo4j.server.CommunityBootstrapper.main(CommunityBootstrapper.java:35)
Caused by: java.lang.ClassCastException: org.eclipse.jetty.server.handler.RequestLogHandler cannot be cast to org.eclipse.jetty.server.handler.HandlerList
	at com.graphaware.server.foundation.bootstrap.GraphAwareBootstrappingFilter.findHandlerList(GraphAwareBootstrappingFilter.java:83)
	at com.graphaware.server.foundation.bootstrap.GraphAwareBootstrappingFilter.bootstrapGraphAware(GraphAwareBootstrappingFilter.java:71)
	at com.graphaware.server.foundation.bootstrap.GraphAwareBootstrappingFilter.init(GraphAwareBootstrappingFilter.java:53)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:138)

**Comment by bachmanm** [comment]
Thanks, this is an embarrassing regression, will be fixed in next release (a few days max)
