### ISSUE TITLE
The ResourceConfig instance does not contain any root resource classes

### ISSUE THREAD

**Issue by superkruger** [graphaware/neo4j-framework#43]
neo4j server 2.3.2 community edition fails to start up when adding the graphaware plugin.
I tried with jdk 7 and 8.

Here's the log:
2016-03-04 09:46:23.859+0100 ERROR Failed to start Neo4j: Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-1d5378a2@386e8717==org.neo4j.server.web.NeoServletContainer,-1,false Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-1d5378a2@386e8717==org.neo4j.server.web.NeoServletContainer,-1,false
org.neo4j.server.ServerStartupException: Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-1d5378a2@386e8717==org.neo4j.server.web.NeoServletContainer,-1,false
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:67)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:234)
	at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:97)
	at org.neo4j.server.CommunityBootstrapper.start(CommunityBootstrapper.java:48)
	at org.neo4j.server.CommunityBootstrapper.main(CommunityBootstrapper.java:35)
Caused by: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-1d5378a2@386e8717==org.neo4j.server.web.NeoServletContainer,-1,false
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:395)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:379)
	at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:182)
	at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:377)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:222)
	... 3 more
Caused by: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
	at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
	... 22 more

**Comment by ikwattro** [comment]
Hi,

Looks like a permissions problem on the plugins, can you output the result of `ls -alh plugins/` 

Thanks

**Comment by superkruger** [comment]
Thanks for the fast response Christophe.

Doesn't look like permissions:

drwxr-xr-x@  4 jaco  staff   136B  4 Mar 09:38 .
drwxr-xr-x@ 15 jaco  staff   510B  4 Mar 09:38 ..
-rw-r--r--@  1 jaco  staff   273B 13 Jan 00:01 README.txt
-rw-r--r--@  1 jaco  staff   397K  4 Mar 09:17 graphaware-server-community-all-2.3.2.37.jar

**Comment by bachmanm** [comment]
Do you have `org.neo4j.server.thirdparty_jaxrs_classes=com.graphaware.server=/graphaware` in neo4j-server.properties?

**Comment by superkruger** [comment]
yes indeed:

# graphaware
org.neo4j.server.thirdparty_jaxrs_classes=com.graphaware.server=/graphaware

**Comment by bachmanm** [comment]
Where did you get the jar? Looks small to me. Try products.graphaware.com

**Comment by superkruger** [comment]
O yeah, should be heaps bigger... Must have corrupted or something during download... weird.
From: https://github.com/graphaware/neo4j-framework#download

Thanks for the quick help, all sorted now ;)

**Comment by ikwattro** [comment]
You're welcome, 

If later on you want to share your experience and your thoughts of the framework, let us know, we will be happy to hear it.
