### ISSUE TITLE
Issue since upgrade to neo4j 3.2

### ISSUE THREAD

**Issue by gottfriedsz** [graphaware/neo4j-framework#73]
Upgraded to neo4j 3.2 and the latest version of the ga framework (graphaware-server-community-all-3.1.4.49.jar) is not compatible with it. Here is the stacktrace from the console.

```
Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /etc/neo4j
  logs:         /var/log/neo4j
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/run/neo4j
Starting Neo4j.
2017-05-12 21:34:24.535+0000 INFO  ======== Neo4j 3.2.0 ========
2017-05-12 21:34:24.684+0000 INFO  Starting...
2017-05-12 21:34:25.186+0000 INFO  Bolt enabled on 0.0.0.0:57687.
2017-05-12 21:34:25.203+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@263cfb77' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@263cfb77' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@263cfb77' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:107)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:80)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@263cfb77' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:209)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@3b08a691' failed to initialize. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
	... 9 more
Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/Setting;
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.<clinit>(RuntimeKernelExtension.java:79)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtensionFactory.newInstance(RuntimeKernelExtensionFactory.java:52)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtensionFactory.newInstance(RuntimeKernelExtensionFactory.java:30)
	at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:68)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 12 more
2017-05-12 21:34:25.204+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by szing** [comment]
actucally the question is when a version of ga will be available for neo4j 3.2.

thanks

**Comment by ikwattro** [comment]
Count a couple of days

**Comment by bachmanm** [comment]
We will have to wait for 3.2.1 - there's a bug in 3.2.0 around new native label-based indexing that prevents us from upgrading. Stay tuned.

**Comment by szing** [comment]
Ok, thanks for the update

**Comment by aoighost** [comment]
Any news on a fix?

**Comment by bachmanm** [comment]
3.2.1 was released on 13th June. Releasing 3.2.3 now...
