### ISSUE TITLE
Handle live backups gracefully

### ISSUE THREAD

**Issue by jasperblues** [graphaware/neo4j-framework#86]
Steps to repro: 

- Install a module, eg Neo4j-expire
- Run a live backup

Expected: 

Gracefully logs that DB is backing up, resumes when done. 

Actual: 

Exception is logged: 

```Exception in thread "GraphAware Starter" org.neo4j.kernel.impl.core.ThreadToStatementContextBridge$BridgeDatabaseShutdownException: This database is shutdown.
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.checkIfShutdown(ThreadToStatementContextBridge.java:98)
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.hasTransaction(ThreadToStatementContextBridge.java:```

**Comment by bachmanm** [comment]
Hey Jasper, I think the stack trace got trimmed, could you post the full one pls?

**Comment by jasperblues** [comment]
```[START] - CREATE BACKUP
Destination is not empty, doing incremental backup...
2018-01-10 11:07:20.901+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2018-01-10 11:07:20.931+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID LM, using com.graphaware.neo4j.lifecycle.LifecycleModuleBootstrapper
2018-01-10 11:07:21.085+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
Doing consistency check...
2018-01-10 11:08:06.414+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV3_2[v0.A.8] record format from store /home/ubuntu/vampr.db
2018-01-10 11:08:06.417+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Format not configured. Selected format from the store: RecordFormat:StandardV3_2[v0.A.8]
Exception in thread "GraphAware Starter" org.neo4j.kernel.impl.core.ThreadToStatementContextBridge$BridgeDatabaseShutdownException: This database is shutdown.
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.checkIfShutdown(ThreadToStatementContextBridge.java:98)
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.hasTransaction(ThreadToStatementContextBridge.java:44)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.isInOpenTransaction(ClassicCoreSPI.java:201)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:576)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:384)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTx(GraphDatabaseFacade.java:372)
	at com.graphaware.runtime.metadata.GraphPropertiesMetadataRepository.persistModuleMetadata(GraphPropertiesMetadataRepository.java:108)
	at com.graphaware.runtime.metadata.GraphPropertiesMetadataRepository.persistModuleMetadata(GraphPropertiesMetadataRepository.java:98)
	at com.graphaware.runtime.manager.BaseModuleManager.persistMetadata(BaseModuleManager.java:217)
	at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:158)
	at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:125)
	at com.graphaware.runtime.TxDrivenRuntime.loadMetadata(TxDrivenRuntime.java:130)
	at com.graphaware.runtime.ProductionRuntime.loadMetadata(ProductionRuntime.java:80)
	at com.graphaware.runtime.BaseGraphAwareRuntime.startModules(BaseGraphAwareRuntime.java:154)
	at com.graphaware.runtime.TxDrivenRuntime.startModules(TxDrivenRuntime.java:146)
	at com.graphaware.runtime.ProductionRuntime.startModules(ProductionRuntime.java:70)
	at com.graphaware.runtime.BaseGraphAwareRuntime.start(BaseGraphAwareRuntime.java:134)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.lambda$start$9(RuntimeKernelExtension.java:117)
	at java.lang.Thread.run(Thread.java:748)
....................  10%
....................  20%
```

**Comment by ikwattro** [comment]
@jasperblues What version is it, tried to replicate with 3.3.1 and couldn't

**Comment by jasperblues** [comment]
@ikwattro it is neo4j 3.2.2, with the previous version of the FW. Plan to update soon, will let you know if  I can still repro.

**Comment by bachmanm** [comment]
@jasperblues could you check if this is an issue on 3.3.2 or 3.3.1 still? Thanks!

**Comment by jasperblues** [comment]
Yes, I plan to upgrade to 3.3.x once I know what is happening with #87, meantime will check asap.

**Comment by jasperblues** [comment]
Does not happen on 3.3.2
