### ISSUE TITLE
Cannot find Audit module

### ISSUE THREAD

**Issue by kingo999** [graphaware/neo4j-framework#98]
I cannot seem to find the Audit module: com.graphaware.module.AuditModuleBootstrapper.
2019-10-25 09:08:12.999+0000 INFO  Bootstrapping module with order 2, ID FSM, using com.graphaware.module.AuditModuleBootstrapper
2019-10-25 09:08:13.000+0000 ERROR Unable to bootstrap module 2 com.graphaware.module.AuditModuleBootstrapper
java.lang.ClassNotFoundException: com.graphaware.module.AuditModuleBootstrapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

Has this module been removed from the latest version?
I checked in community and server editions jar files and do not see any reference to Audit - 3.5.11.54

**Comment by ikwattro** [comment]
Audit is a commercial offering only. There is no open-source releases. Feel free to send an e-mail to info@graphaware.com for more information.
